# -*- coding: utf-8 -*-
"""exercize4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ow2u2yH4bgRFVojEDubWHawDn8qn20hf
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.simplefilter("ignore", DeprecationWarning)
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
data = load_iris()
X,y = data.data,data.target
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
print("trainng data")
print(X_train)
print("testing data")
print(X_test)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
accuracy = model.score(X_test_scaled,y_test)
print("model accuracy",accuracy)
print("learned model weights:")
print(model.coef_)